spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usertask
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

